
name: Publish Docker - osnode-init

on:
    workflow_dispatch:
      inputs:
        tags:
          description: 'Release Tags'

jobs:
    publish_dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.18.10'

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                push: true
                tags: beclab/osnode-init:v${{ github.event.inputs.tags }}
                file: Dockerfile

